#!/usr/bin/env node
/**
 * Downloads the site's webfonts from Google Fonts and writes them, plus a
 * local stylesheet, into fonts/. Run only when FAMILIES below changes:
 *
 *   node tools/fetch-fonts.mjs
 *
 * The site serves these files itself rather than linking fonts.googleapis.com.
 * That is worth the committed binaries three times over:
 *
 *  1. The Google Fonts <link> is render-blocking and costs two extra DNS +
 *     TLS handshakes before a single headline can paint.
 *  2. It removes a third party from the request path of every visitor, which
 *     is the reason the CSP no longer needs to allow fonts.gstatic.com.
 *  3. tools/build-images.mjs renders the share card in a sandbox with no route
 *     to fonts.googleapis.com. Fetching at render time failed silently there -
 *     Chromium fell back to DejaVu Sans and produced an off-brand card that
 *     shipped before anyone noticed. Local files cannot fail that way.
 *
 * Both families are SIL Open Font License 1.1, which permits self-hosting.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DEST = join(ROOT, 'fonts');

// Keep in sync with --font-display / --font-body in index.html.
//
// Weights are a RANGE, not a list, which makes Google return one variable font
// per subset covering every weight in between. That is not a rounding-error
// saving: the four static Inter weights are 47KB each, while a single variable
// Inter that does all four - and every weight between them - is 48KB.
const FAMILIES = [
  { name: 'Plus Jakarta Sans', from: 600, to: 800 },
  { name: 'Inter', from: 400, to: 800 },
];

// Only Latin. The full Google response also carries Cyrillic, Greek and
// Vietnamese subsets, which would roughly triple the bytes for glyphs this
// site never renders.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

// Asking as an old browser gets TTF instead of WOFF2, which is ~2x the size.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const curl = (url, out) => {
  const args = ['-sSL', '--fail', '--max-time', '60', '-A', UA, url];
  if (out) args.push('-o', out);
  return execFileSync('curl', args, out ? undefined : { encoding: 'utf8' });
};

rmSync(DEST, { recursive: true, force: true });
mkdirSync(DEST, { recursive: true });

const blocks = [];

for (const family of FAMILIES) {
  const spec = `${family.name.replace(/ /g, '+')}:wght@${family.from}..${family.to}`;
  const css = curl(`https://fonts.googleapis.com/css2?family=${spec}&display=swap`);

  // Google emits `/* subset */` immediately before each @font-face it labels.
  const parts = css.split(/\/\*\s*([a-z-]+)\s*\*\//i).slice(1);
  for (let i = 0; i < parts.length; i += 2) {
    const subset = parts[i].trim();
    const face = parts[i + 1];
    if (!KEEP_SUBSETS.has(subset)) continue;

    const url = face.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;

    const slug = family.name.toLowerCase().replace(/ /g, '-');
    const file = `${slug}-${subset}.woff2`;
    curl(url, join(DEST, file));

    blocks.push(
      face
        .replace(/url\(https:\/\/[^)]+\.woff2\)/, `url('${file}')`)
        .replace(/^\s+|\s+$/g, '')
        .replace(/\n\s*/g, '\n  '),
    );
  }
}

const header = `/* Generated by tools/fetch-fonts.mjs - do not edit by hand.
   ${FAMILIES.map((f) => `${f.name} ${f.from}-${f.to}`).join(', ')}
   Latin subsets only. SIL Open Font License 1.1. */\n\n`;

writeFileSync(join(DEST, 'fonts.css'), header + blocks.join('\n\n') + '\n');

const files = readdirSync(DEST).filter((f) => f.endsWith('.woff2'));
const total = files.reduce((n, f) => n + statSync(join(DEST, f)).size, 0);
for (const f of files.sort()) {
  console.log(`  ${f.padEnd(40)} ${(statSync(join(DEST, f)).size / 1024).toFixed(1).padStart(7)} KB`);
}
console.log(`\n${files.length} files, ${(total / 1024).toFixed(1)} KB total -> ${DEST}`);
if (!existsSync(join(DEST, 'fonts.css'))) throw new Error('fonts.css was not written');
