#!/usr/bin/env node
/**
 * Re-encodes oversized raster images in images/ to WebP, using headless
 * Chromium as the codec so the repo needs no native image dependency.
 *
 *   node tools/optimize-images.mjs           # report only
 *   node tools/optimize-images.mjs --write   # write .webp next to the source
 *
 * Only screenshots and photographs belong here. Do not run it over the brand
 * marks in assets/logos - those are SVG and must stay vector. The favicon and
 * OG PNGs are generated by tools/build-images.mjs and are already small.
 */

import { spawn } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync, statSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'images');
const WRITE = process.argv.includes('--write');

// Anything at or above this is worth converting; below it the WebP saving is
// swamped by the cost of an extra file to keep in sync.
const MIN_BYTES = 60 * 1024;
const QUALITY = 0.86;

function findChrome() {
  const pwRoot = process.env.PLAYWRIGHT_BROWSERS_PATH || '/opt/pw-browsers';
  const candidates = [process.env.CHROME_BIN].filter(Boolean);
  if (existsSync(pwRoot)) {
    for (const e of readdirSync(pwRoot)) {
      if (e.startsWith('chromium-')) candidates.push(join(pwRoot, e, 'chrome-linux', 'chrome'));
    }
  }
  candidates.push('/usr/bin/chromium', '/usr/bin/chromium-browser', '/usr/bin/google-chrome');
  const found = candidates.find((p) => p && existsSync(p));
  if (!found) throw new Error('Could not find Chromium. Set CHROME_BIN and re-run.');
  return found;
}

const targets = readdirSync(SRC)
  .filter((f) => ['.png', '.jpg', '.jpeg'].includes(extname(f).toLowerCase()))
  .map((f) => ({ file: f, bytes: statSync(join(SRC, f)).size }))
  .filter((t) => t.bytes >= MIN_BYTES)
  .sort((a, b) => b.bytes - a.bytes);

if (!targets.length) {
  console.log(`Nothing in images/ is at or above ${(MIN_BYTES / 1024).toFixed(0)} KB.`);
  process.exit(0);
}

const profile = mkdtempSync(join(tmpdir(), 'ss-opt-'));
const chrome = spawn(findChrome(), [
  '--headless', '--disable-gpu', '--no-sandbox', '--remote-debugging-port=0', `--user-data-dir=${profile}`, 'about:blank',
], { stdio: ['ignore', 'pipe', 'pipe'] });

const wsUrl = await new Promise((res, rej) => {
  let buf = '';
  const t = setTimeout(() => rej(new Error('Timed out waiting for Chromium')), 30000);
  chrome.stderr.on('data', (c) => {
    buf += c;
    const m = buf.match(/DevTools listening on (ws:\/\/\S+)/);
    if (m) { clearTimeout(t); res(m[1]); }
  });
  chrome.on('exit', (code) => { clearTimeout(t); rej(new Error(`Chromium exited ${code}`)); });
});

const ws = new WebSocket(wsUrl);
await new Promise((r) => ws.addEventListener('open', r, { once: true }));
let seq = 0;
const pending = new Map();
ws.addEventListener('message', (ev) => {
  const m = JSON.parse(ev.data);
  if (m.id && pending.has(m.id)) {
    const q = pending.get(m.id); pending.delete(m.id);
    m.error ? q.reject(new Error(m.error.message)) : q.resolve(m.result);
  }
});
const send = (method, params = {}, sid) => new Promise((resolve, reject) => {
  const id = ++seq;
  pending.set(id, { resolve, reject });
  ws.send(JSON.stringify(sid ? { id, method, params, sessionId: sid } : { id, method, params }));
});

const { targetId } = await send('Target.createTarget', { url: 'about:blank' });
const { sessionId } = await send('Target.attachToTarget', { targetId, flatten: true });

let saved = 0;
for (const t of targets) {
  const dataUri = `data:image/${extname(t.file).slice(1).replace('jpg', 'jpeg')};base64,`
    + readFileSync(join(SRC, t.file)).toString('base64');

  const { result } = await send('Runtime.evaluate', {
    awaitPromise: true, returnByValue: true,
    expression: `(async () => {
      const img = new Image();
      img.src = ${JSON.stringify(dataUri)};
      await img.decode();
      const c = document.createElement('canvas');
      c.width = img.naturalWidth; c.height = img.naturalHeight;
      c.getContext('2d').drawImage(img, 0, 0);
      return JSON.stringify({
        w: img.naturalWidth, h: img.naturalHeight,
        webp: c.toDataURL('image/webp', ${QUALITY}).split(',')[1],
      });
    })()`,
  }, sessionId);

  const { w, h, webp } = JSON.parse(result.value);
  const bytes = Buffer.from(webp, 'base64');
  const out = basename(t.file, extname(t.file)) + '.webp';
  const pct = (100 - (bytes.length / t.bytes) * 100).toFixed(0);

  console.log(`  ${t.file.padEnd(28)} ${w}x${h}  ${(t.bytes / 1024).toFixed(0).padStart(4)} KB -> ${(bytes.length / 1024).toFixed(0).padStart(4)} KB  (-${pct}%)  ${out}`);
  if (WRITE) {
    writeFileSync(join(SRC, out), bytes);
    saved += t.bytes - bytes.length;
  }
}

ws.close(); chrome.kill();
await new Promise((r) => { chrome.once('exit', r); setTimeout(r, 4000); });
try { rmSync(profile, { recursive: true, force: true }); } catch { /* best effort */ }

console.log(WRITE
  ? `\nWrote ${targets.length} file(s), ${(saved / 1024).toFixed(0)} KB saved. Update the <img> tags to point at them.`
  : `\nDry run. Re-run with --write to emit the .webp files.`);
